# Generated by Django 2.1.dev20171109164034 on 2017-12-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]