# Generated by Django 2.0.1 on 2018-01-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006'),
        ('website', '0004_auto_20171215_1558'),
    ]

    operations = [
    ]
